/*

Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

*/

const MAX = 4000000;
let prev = 1;
let next = 2;
let sumEvens = 2;

while (next <= MAX) {
  const temp = next;
  next = prev + next;
  prev = temp;
  if (!(next % 2)) sumEvens += next;
}

console.log(sumEvens);
